### ISSUE TITLE
aha-table.html in dist folder outdated

### ISSUE THREAD

**Issue by mixmatch** [liuwenchao/aha-table#10]
Does not work with Polymer 1.0:
Uncaught TypeError: prototype.registerCallback is not a function

**Comment by mixmatch** [comment]
attempting to use src folder causes issues due to following difference:
dist:
```html
<link rel="import" href="../../polymer/polymer.html">
```
src:
```html
<link rel="import" href="../bower_components/polymer/polymer.html">
```

**Comment by liuwenchao** [comment]
@mixmatch please try v2.0.3, and http://liuwenchao.github.io/aha-table/ in your browser, let me know if the demo page doesn't run for you either (please provide OS version and browser version), otherwise you can compare the codes between demo page and your page to see the difference.

there's no need to try src file as every release in aha-table is done by `grunt deploy` which will sync the content between src and dist, files in src are used for development environment.

**Comment by wintersandroid** [comment]
I have the same error - the dist file is definatly outdated, within the zip for the latest and previous versions the element is a "polymer-element" not a "dom-module" as in the src folder..

You need to check the deploy you are using!!

An eaiser way to package when using github is to have the source in the root of the folder, and then all you need to do to create a version is "bower version (major/minor/patch) which will then create the version in github.. Then there is no need for "src" and "dist" directories..

**Comment by liuwenchao** [comment]
Thanks @wintersandroid and @mixmatch I noticed the issue, here's the original discussion: https://github.com/webcomponents/polymer-boilerplate/issues/17 , I have fixed it. Please try v2.0.4
